# Site settings
title: .NET FM
email: hi@dotnet.net
description: > # this means to ignore newlines until "baseurl:"
  额，我竟无语凝噎...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dotnet.fm" # the base hostname & protocol for your site
twitter_username: dotnetalk
github_username: dotnetalk
weibo_username: dotnetalk

# Build settings
markdown: kramdown
