# Site settings
title: .NET FM
email: hi@dotnet.net
description: > # this means to ignore newlines until "baseurl:"
  致力于推广 .NET 和微软技术的一档非典型严肃播客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dotnet.fm" # the base hostname & protocol for your site
twitter_username: dotnetalk
github_username: dotnetalk
weibo_username: dotnetalk

# Build settings
markdown: kramdown
